spring:
    application:
        name: sample-service2
#   Percentage of logs export to zipkin server
    sleuth:
        stream:
            enabled: false
        sampler:
            percentage: 0.5
    zipkin:
#       For enabling Zipkin Client for this Microservice
        enabled: false 
#       Server Url
        baseUrl: http://localhost:9411
        locator:
            discovery:
                enabled: false
#   Kafka Configuration using spring-cloud-stream
    cloud:
        stream: 
            default:
                contentType: application/json
            bindings:
                inputchannel:
                    destination: abcd
                    group: consumergroup1
                    consumer.resetOffsets: true
                    consumer.startOffset: latest
                testchannel:
                    destination: sampletopic
                    group: consumergroup2
                    consumer.resetOffsets: true
                    consumer.startOffset: latest
                    
            kafka:
                binder:
                    zkNodes: kafka
                    brokers: kafka
                    

# Server Information
server:
    port: 6070
    



